services:
  - type: web
    name: scrapvex-backend
    env: node
    region: singapore
    buildCommand: PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer npx puppeteer browsers install chrome && npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://amjadkhan33411_db_user:06032001@cluster0.dgccilx.mongodb.net/scrapvex?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: scrapvex_secret_key_2026_jk_digital
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
